#!/usr/bin/python

import socket
import os
# import time

def get_ip_address():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    return s.getsockname()[0]

ipaddr = get_ip_address()

# print "Current IP Address: " + ipaddr

with open("./app/config/settings.js", "r+") as f:
     old = f.read() # read everything in the file

     stIdx = old.index("ws://")
     endIdx = old.index(":3000/websocket")

     str = old[stIdx+5:endIdx]

     f.seek(0)
     f.write(old.replace(str, ipaddr))
     f.close()

# os.system("adb kill-server");
# print "adb server restart..."
# time.sleep(2)

os.system("react-native run-android");

print "\n\nCurrent IP Address: " + ipaddr + "\n"